### ISSUE TITLE
ipv6 connection to devtracksys

### ISSUE THREAD

**Issue by num81** [ADumaine/secnodetracker#1]
Currently unable to make ipv6 connections to the secure node tracker.

zen@zenpool:~/zencash/secnodetracker$ node app.js
CPU Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz  cores=6  speed=2194
Pool app version: 0.0.5
MemTotal: 9.99GB  MemFree: 4.15GB  MemAvailable: 6.08GB  SwapTotal: 2.04GB  SwapFree: 2.04GB
2017-08-31 06:45:51 GMT -- No connection to server
2017-08-31 06:46:51 GMT -- No connection to server
2017-08-31 06:47:51 GMT -- No connection to server
2017-08-31 06:48:51 GMT -- No connection to server

I can see that the AAAA record for devtracksys.secnodes.com [fe80::f03c:91ff:fe3e:1669] is now live however unable to connect.

I have also tried to change the tracker url in the setup to http://[fe80::f03c:91ff:fe3e:1669]/ however it has the same results.

**Comment by num81** [comment]
This is now working after the update of the DNS records for the tracker to http://[2600:3c02::f03c:91ff:fe3e:1669]/

**Comment by num81** [comment]
Going to reopen this issue.

Setup a new node that had not connected with ipv4, receive the following error when trying to connect;


Pool app version: 0.0.5
MemTotal: 3.94GB  MemFree: 0.38GB  MemAvailable: 0.64GB  SwapTotal: 4.09GB  SwapFree: 4.09GB
2017-09-01 12:26:57 GMT -- Connected to node pool server
{ Error: getaddrinfo EAI_ADDRFAMILY 2001:8332
    at Object._errnoException (util.js:1041:11)
    at errnoException (dns.js:58:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
  cause:
   { Error: getaddrinfo EAI_ADDRFAMILY 2001:8332
       at Object._errnoException (util.js:1041:11)
       at errnoException (dns.js:58:15)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
     code: 'EAI_ADDRFAMILY',
     errno: 'EAI_ADDRFAMILY',
     syscall: 'getaddrinfo',
     hostname: '2001',
     host: '2001',
     port: '8332' },
  isOperational: true,
  code: 'EAI_ADDRFAMILY',
  errno: 'EAI_ADDRFAMILY',
  syscall: 'getaddrinfo',
  hostname: '2001',
  host: '2001',
  port: '8332' }

**Comment by num81** [comment]
leaving the local store for rpcallowip empty will allow the secure node to boot with an ipv6 address

either ::1 or 127.0.0.1 will cause an exception to occour

2017-09-02 02:34:16 GMT -- Connected to node pool server
{ RpcError: Not Found
    at get (/home/zen/zencash/secnodetracker/node_modules/bitcoin-core/dist/src/parser.js:34:11)
    at Client.rpc (/home/zen/zencash/secnodetracker/node_modules/bitcoin-core/dist/src/parser.js:81:14)
    at Client.tryCatcher (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/zen/zencash/secnodetracker/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/zen/zencash/secnodetracker/node_modules/request/request.js:188:22)
    at emitTwo (events.js:130:20)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/zen/zencash/secnodetracker/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/zen/zencash/secnodetracker/node_modules/request/request.js:1091:12) message: 'Not Found', name: 'RpcError', code: 404 }
Unable to connect to zend. Please check the zen rpc settings and ensure zend is running

**Comment by num81** [comment]
This issue has been fixed in the IPv6 pull request

**Comment by ADumaine** [comment]
pull request merged.
pull request fixed.
